### ISSUE TITLE
Cannot get docker installation to use existing bitcoind

### ISSUE THREAD

**Issue by docker-prog** [shesek/spark-wallet#106]
I'm specifying my existing data directory with -v ~/.bitcoin:/path/to/blocks/ but the system still populates the directory at /home/user/.spark-docker/bitcoin and starts downloading blocks data into it.

**Comment by shesek** [comment]
You should be using `-v ~/.bitcoin:/etc/bitcoin`, where `~/.bitcoin` should be replaced with the path to your bitcoind data directory on the host machine, and `/etc/bitcoin` should be kept as-is.

Can you try that and report back?

**Comment by shesek** [comment]
Closing, please report back if you're still having issues.
