### ISSUE TITLE
Not able to run on a path other than /

### ISSUE THREAD

**Issue by renepickhardt** [shesek/spark-wallet#11]
When starting spark-wallet node.js server and pipe it behind some proxy server to my site I can only pipe it to the root directory of the domain since all the `js` and `css` files which are loaded asychronously are loaded from `/ `

**Comment by shesek** [comment]
This should work if you access it with  a trailing slash, i.e. `http://hostname/subdirectory/` and not `http://hostname/subdirectory`. Is this sufficient?

**Comment by shesek** [comment]
I'm closing this, please report back if you're still having issues.
