### ISSUE TITLE
Error message: ETIMEDOUT 107.154.248.133:443

### ISSUE THREAD

**Issue by kalibox** [shesek/spark-wallet#111]
Hi,

My Spark wallet instance has been running OK but starting today I'm seeing the following error messages on the terminal:

Error: connect ETIMEDOUT 107.154.248.133:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

Any ideas what this may be about?

Thanks

**Comment by shesek** [comment]
It's not able to reach the bitstamp API to fetch the current BTC/USD exchange rate. This means that the exchange rate will be missing/outdated, but everything should work otherwise.

**Comment by kalibox** [comment]
Thank you, yes you're right. All good now.
