### ISSUE TITLE
Features requests

### ISSUE THREAD

**Issue by darosior** [shesek/spark-wallet#113]
I've been using spark wallet for the last week and had thought of some features that could be useful:
- Use a Qr code to get a node specs (url and ip) when funding a channel
- Choose fees (normal, urgent, prio) to fund a channel
- An interface (like a CLI) to use plugins, for example to be able to rebalance channels from our mobile

**Comment by shesek** [comment]
> Use a Qr code to get a node specs (url and ip) when funding a channel

Yes, this is definitely needed. I created #42 to track this awhile back, but didn't get to this yet.

> An interface (like a CLI) to use plugins, for example to be able to rebalance channels from our mobile

You can issue rpc commands using the rpc console page, which becomes available if you enable expert mode. Clicking the version number in the bottom-left will turn on expert mode, which will add an "RPC Console" button to the main page.

> Choose fees (normal, urgent, prio) to fund a channel

You can set the fees if you enable expert mode. This definitely shouldn't be considered an expert feature, but the UI requires some improvements before making it an official feature.

**Comment by darosior** [comment]
Thanks !
