### ISSUE TITLE
different balance on different clients

### ISSUE THREAD

**Issue by ulrichard** [shesek/spark-wallet#115]
When I connect to my spark server from two different clients, they show different balances at the top right of the browser window. More precisely, most clients agree, but one showed a lower balance than the others for a couple of months. The one that differs is on the local network and appears to look like an older version of the UI without listing funds in channels and utxos separately.

**Comment by shesek** [comment]
The way the top-right balance is calculated [was changed](https://github.com/shesek/spark-wallet/blob/master/CHANGELOG.md#026---2019-06-07) a few months ago, so it makes sense that older client versions display it differently.

Can you try issuing a hard refresh (Ctrl-Shift-R) and see this gets you to the latest version?

Another potential cause is an outdated Spark server, which means that the web interface will also be outdated when accessed using a web browser, but not when accessing the same server using a recent version of the android/desktop applications.

**Comment by ulrichard** [comment]
Ctrl-Shift-R solved it. 
Thanks a lot!
