### ISSUE TITLE
Could not install server side

### ISSUE THREAD

**Issue by parmax** [shesek/spark-wallet#116]
npm install -g spark-wallet                                                                                npm ERR! addLocal Could not install /usr/lib/node_modules/spark-wallet/lightning-client@github:shesek/lightning-client-js#ccb565d889803bce65a1a0e42d3948332a7fcdac
npm ERR! path /usr/lib/node_modules/spark-wallet/lightning-client@github:shesek/lightning-client-js#ccb565d889803bce65a1a0e42d3948332a7fcdac
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/usr/lib/node_modules/spark-wallet/lightning-client@github:shesek/lightning-client-js#ccb565d889803bce65a1a0e42d3948332a7fcdac'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-09T15_50_59_252Z-debug.log

**Comment by parmax** [comment]
I fix it npm install -g npm

**Comment by shesek** [comment]
Try installing with `sudo npm install -g spark-wallet`, or follow [the instructions here](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory) to install to it into your home directory without requiring `sudo`.
