### ISSUE TITLE
listpayments deprecated

### ISSUE THREAD

**Issue by parmax** [shesek/spark-wallet#117]
I am updating c-lightning to 0.7.2.1 and my spark-wallet-portable don't work after it.
I changed listpayments to listsendpays in spark-wallet server side code. Web wallet is working now.
Please fix it.

**Comment by shesek** [comment]
As mentioned in #112, this [was already implemented](https://github.com/shesek/spark-wallet/commit/70d97a9841b5caadd36955304081430b2c45b6ee) a couple months back, but still wasn't released in a new version. I'll try to hurry up the release of v0.2.9 with this change.

Closing this in favor of #112, will post updates there.

**Comment by shesek** [comment]
One quick workaround until the new release is configuring your c-lightning node with `allow-deprecated-apis=true`.

**Comment by parmax** [comment]
This is not worked with v0.7.2.1
