### ISSUE TITLE
Version still showing 0.2.8 on browser

### ISSUE THREAD

**Issue by kalibox** [shesek/spark-wallet#120]
Hi,

Thanks for the updated version of Spark-Wallet. 

I noticed that the cli shows the updated version after upgrading via npm:

user@spark:~ $ spark-wallet --version
0.2.9

Navigating to it via a browser still shows 0.2.8: https://i.imgur.com/itDtzj0.png

This is not a big issue but just wanted to bring it to your attention.

Thanks!

**Comment by shesek** [comment]
Try a hard refresh with Ctrl-shift-r to clear your browser cache.

**Comment by shesek** [comment]
Closing, please report back if you're still having issues.
