### ISSUE TITLE
Display EUR currency in request payment

### ISSUE THREAD

**Issue by Darth-Coin** [shesek/spark-wallet#125]
It would be very helpful for merchants using Spark in-store payments, to have the option to switch to EUR amount of request payment.
Let's say I have a shoes shop, accepting BTC/LN.
I open my spark wallet on mobile and want to put the amount of request in EUR for a pair of shoes, 50€. The Spark wallet doesn't have this option now, only in sats, BTC or USD.
Also to have an option to setup the average rate exchange or a specific exchange price/index.

**Comment by Klexx** [comment]
Duplicate of #12

**Comment by shesek** [comment]
Thanks @Klexx, closing in favor of #12.
