### ISSUE TITLE
Withdrawing funds using Spark RPC console

### ISSUE THREAD

**Issue by RhinoAK** [shesek/spark-wallet#126]
Whenever I attempt to issue the command `withdraw _bech_address_ satoshi_amount ` I keep getting Cannot afford transaction even though I have 900000+ sats on the node. My question is what limitation does using this command have in terms of the number of uses? The command worked once before where I was only able to withdraw 350000 sats. Also when attempting the same command with the parameter of "all" I get the same error.

**Comment by shesek** [comment]
This seems like an issue not specifically related to spark, but more generally to c-lightning. Maybe try asking on #c-lightning at freenode?

**Comment by RhinoAK** [comment]
How can this not be related to Spark where in this is where the issue presented itself?
