### ISSUE TITLE
v0.2.10 bug

### ISSUE THREAD

**Issue by k3tan172** [shesek/spark-wallet#128]
Upgraded to v0.2.10 server and client.

"Channels" and "Deposit" buttons no longer work in v0.2.10 clients. Tested on Mac and Android.
v0.2.9 seems to work fine.

**Comment by junity42** [comment]
I have the same issue with the new version, plus on the same page, the < Spark link on the top left doesn't work either. I don't know if it helps, but I'm getting this response from terminal:
POST /rpc 200 6.752 ms - 556
Tested on Linux Firefox.

**Comment by Darth-Coin** [comment]
Same here, tested on Android 8.1.0, c-ln version 0.7.3.88gf075b87, bitcoind 0.18.1

**Comment by shesek** [comment]
Thanks for the bug report. Looks like this was due to a typo that slipped in, should be fixed by 888eb4f795c3af82f7fc4ed229e562cb6f862fea. Will release this as v0.2.11 soon.

**Comment by shesek** [comment]
Released as v0.2.11. Apologies for the delay, I ran into some complications building the cordova app for the new release.

**Comment by Darth-Coin** [comment]
> Released as v0.2.11. Apologies for the delay, I ran into some complications building the cordova app for the new release.

No need for apologize. You are doing a great work. I am happy that you are very responsive to users.

**Comment by k3tan172** [comment]
Thanks @shesek. I downloaded the apk file for Android, it can no longer connect to the spark-wallet server, says error connecting. Also ```npm install -g spark-wallet``` installs v0.2.10, not v0.2.11.

**Comment by Darth-Coin** [comment]
For me works fine. I just tested on Android and Windows desktop. All OK. Just received a payment :)

**Comment by k3tan172** [comment]
Downgraded to v0.2.9 and it connects. I install the v0.2.11 apk and it doesn't connect to server. I'll have to do some troubleshooting, seems odd.

**Comment by Darth-Coin** [comment]
Seems that you have some issues with your secret key from your C-LN server. Check that.
Yes, after I installed from apk, was asking me to connect to the server and all the fields were empty. I just filled them, IP, port and secret key and works just fine.

**Comment by k3tan172** [comment]
I don't think it's my secret key. It works fine on my mac and linux. Just android is the problem. spark-wallet server hasn't upgraded to v0.2.11 on npm, so I'll wait for that.

**Comment by Darth-Coin** [comment]
> I don't think it's my secret key. It works fine on my mac and linux. Just android is the problem. spark-wallet server hasn't upgraded to v0.2.11 on npm, so I'll wait for that.

I didn't updated too. I still have 0.2.9 server side. I didn't change anything on server side.

**Comment by shesek** [comment]
> But I see no update on Play Store.

Is this still the case? Play Store app updates take some time to fully roll out.

> I downloaded the apk file for Android, it can no longer connect to the spark-wallet server, says error connecting.

I'm not aware of any changes made since v0.2.9 that could cause this. Can you try accessing the Spark web interface using your mobile web browser instead of through the app and see if that works? You can open the URL you get with `--pairing-url`/`--pairing-qr` in your browser to authenticate and access the wallet.

**Comment by shesek** [comment]
> spark-wallet server hasn't upgraded to v0.2.11 on npm

That's very odd!

I can still see the results of `npm publish` in my terminal logs with a success message saying that v0.2.11 was published.

I tried publishing again, and I'm getting `403 Forbidden - PUT https://registry.npmjs.org/spark-wallet - You cannot publish over the previously published versions: 0.2.11`.

And yet, it doesn't show up [on npmjs.org](https://www.npmjs.com/package/spark-wallet?activeTab=versions). o_O

I might have to bump the version to v0.2.12 just to get around this... but I'll try digging around for other solutions first.

**Comment by shesek** [comment]
I tried publishing `spark-wallet@0.2.11-release` and tagging it as `latest`. I received a success message, but its still not showing up on npmjs.org. It does sometime take 10-15 minutes to show up though, so I'll keep my fingers crossed and wait some more (-:

**Comment by shesek** [comment]
FYI, it seems like publishing `spark-wallet@0.2.11-release` did work, you should get this if you install the latest with `npm install -g spark-wallet`.

**Comment by sumBTC** [comment]
Yesterday my android app was working fine. Today it suddenly stopped working. I changed nothing. I have now updated to the latest release (0.2.11-release) but I sill can't connect to the server. In a browser it works fine. The url and access key are fine (and they were fine yesterday). Was the app updated today?

**Comment by k3tan172** [comment]
My experience with the Android app as well. Everything works fine - browser, mac, linux but Android app does not connect to server. The app was updated. I recommend uninstalling and downloading the v0.2.9 apk release and installing that. Turn off auto-update on your phone for spark-wallet, otherwise you'll download and install v0.2.11 again.

**Comment by Darth-Coin** [comment]
On my side, everything works well.  
Spark wallet 0.2.11 + Android 8.1.0 + c-ln version 0.7.3.88gf075b87 + bitcoind 0.18.1
I didn't updated anything on server side. Just the mobile client. Browser and desktop app also works fine.
I connect from local IP and also from external IP. Both fine.

**Comment by sumBTC** [comment]
I updated c-lightning to v0.8.0-1-gb14b2b0  yesterday. But after setting the path right for spark-wallet (since c-lightning v0.8.0 creates a directory bitcoin inside .lightning) it worked fine **yesterday** evening.

bitcoind 0.18.0

android: 9

**Comment by Darth-Coin** [comment]
> I updated c-lightning to v0.8.0-1-gb14b2b0 yesterday. But after setting the path right for spark-wallet (since c-lightning v0.8.0 creates a directory bitcoin inside .lightning) it worked fine **yesterday** evening.
> 
> bitcoind 0.18.0
> 
> android: 9

Hmm, when I saw the new c-LN 0.8 I was reticent to update it quickly. I was worried that will happen exactly this.
Did you tried also to update spark server after the update of c-ln ?

**Comment by sumBTC** [comment]
> Did you tried also to update spark server after the update of c-ln ?

No, I only updated c-lightning (and after pointing spark-wallet on the server to .lightning/bitcoin instead of .lightning the android app worked just fine)

**Comment by sumBTC** [comment]
@k3tan172 I've installed the v0.2.9 apk version of the spark-wallet app on android as you suggested and everything is working again as before! On the server I didn't change anything (latest version of c-lightning and spark-wallet). Also turned off automatic updates of apps on my phone. Thanks a lot!

**Comment by k3tan172** [comment]
Hey @sumBTC, when you upgraded to c-lightning v0.8.0, did you have to copy anything over from ```/home/user/.lightning/``` to /home/user/.lightning/bitcoin``` to get your channels or anything like that? Please let me know.

**Comment by sumBTC** [comment]
I should have but c-lightning automatically copied it for me the first time I started my node with the new version. The directory structure now looks like this:

.lightning:
bitcoin/  config  lightningd-bitcoin.pid

.lightning/bitcoin:
hsm_secret
lightningd.sqlite3
gossip_store
lightning-rpc=

and I run spark-wallet with `--ln-path /home/user/.lightning/bitcoin`

**Comment by shesek** [comment]
@k3tan172 Are you also connecting to your server in plaintext (no tls or onion) by any chance? Or is your issue unrelated to #132?

**Comment by k3tan172** [comment]
Ah yes, I am connecting to server in plaintext, and as mentioned by @sumBTC, it never worked without ```--no-tls```. Issue seems to be identical to what is reported in #132. I'll follow that conversation.
