### ISSUE TITLE
cannot connect to c-lightning v0.8.0

### ISSUE THREAD

**Issue by ulrichard** [shesek/spark-wallet#131]
After upgrading c-lightning to version 0.8.0 I get the following, when I try to start spark:
`user@host:~$ spark-wallet 
Lightning client connection error { Error: connect ENOENT /home/user/.lightning/lightning-rpc
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/home/user/.lightning/lightning-rpc' }
uncaughtException, stopping process
Error: connect ENOENT /home/user/.lightning/lightning-rpc
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)`

**Comment by k3tan172** [comment]
I believe the directory you're connecting to needs to change. This change in directory is a result of upgrading to v0.8.0. You'll find the directory should be ```/home/user/.lightning/bitcoin/lightning-rpc``` instead of ```/home/user/.lighting/lightning-rpc```
Let me know if that helps.

**Comment by shesek** [comment]
See #128. I will soon release a new version with 9dcc8ad20c91833f46c928af326fff26cd3dd85d, which will default to using the bitcoin mainnet subdirectory (if it exists).
