### ISSUE TITLE
Some QR codes not read properly in the web QR scanner

### ISSUE THREAD

**Issue by shesek** [shesek/spark-wallet#134]
Reported by @sumBTC at https://github.com/shesek/spark-wallet/issues/55#issuecomment-568768291.

**Comment by shesek** [comment]
@sumBTC I believe https://github.com/shesek/spark-wallet/commit/b3c9345e85a11922cf6dc54f14752dbecbdb2ec9 should resolve this, are you able to test this from master before I make a new release?

**Comment by sumBTC** [comment]
@shesek I would like to test it. I have downloaded the latest master via `git clone` (or later `git pull`) but how do I install the master? I keep seeing the old install (sorry for this basic question but it has been bugging me for some time)

**Comment by shesek** [comment]
If you cloned/pulled now, you should already by on the latest version of the master branch.

You'll need to `npm install` inside the directory, then `npm start -- --ln-path ~/.lightning/bitcoin` to start the development server daemon (note the extra `--`, they need to be there).

The development server does on-the-fly compilation and is therefore slower and takes up more resources. If you want to use it as your actual wallet and not just for testing, you can also pre-compile it with `npm run dist:npm` then start it with `./dist/cli.js <args>`.

**Comment by sumBTC** [comment]
@shesek  Well good I asked :-) 

Yes, the QR scanner worked perfectly now! Wow, pretty amazing how fast you solved that. Thanks a lot.

At least spark-wallet works over tls in a browser and can scan QR codes! Happy Christmas, family deserves some attention now haha

**Comment by shesek** [comment]
Happy Christmas!
