### ISSUE TITLE
Problem with generated password

### ISSUE THREAD

**Issue by shawnyeager** [shesek/spark-wallet#137]
I use 1Password to generate and manage credentials. I generated the following, and was unable to login to spark-wallet:

`4&#Z7U**vbfytrJ47s`

I switched to a word-based password (e.g. one+two+three), and can now sign in.

**Comment by shesek** [comment]
How are you passing the login credentials to Spark? The special characters might require some shell escaping if you're passing them as arguments or as environment variables. It should be easier if you set them inside the `~/.spark-wallet/config` [config file](https://github.com/shesek/spark-wallet#configuration-file).

Note, however, that Spark's default behavior (assuming the user didn't manually set his credentials) is to generate random login credentials the first time you start it and persist them to `~/.spark-wallet/cookie`. You can then use `--pairing-url` to get a URL that will authenticate you using the generated credentials (or `--pairing-qr` to get the same URL as a QR, which is useful for mobile pairing).

**Comment by shesek** [comment]
Closing, please report back if you're still having issues.
