### ISSUE TITLE
C-lightning deprecations

### ISSUE THREAD

**Issue by darosior** [shesek/spark-wallet#142]
Hi,

For your interest https://github.com/ElementsProject/lightning/pull/3603 removes some fields in the API which have been deprecated for several (6 iirc) months.

Namely:
- The `description` field in `sendpay`.
- The `satoshi` field in `fundchannel_start` (now `amount`). Note also this commit https://github.com/ElementsProject/lightning/pull/3603/commits/49e21538cc99e8f7340d174f02b853cc582dfd2a .
- No more `localfeatures` and `globalfeatures` fields in `listnodes`, `listpeers`, `peer_connected`.
- No more `force` bool in `close`.

Just wanted to make sure you were not relying on deprecated behavior before we release the breaking change !

**Comment by shesek** [comment]
Thanks for bringing this to my attention!

Spark does not rely on any of them as far as I recall and I have been testing it with `allow-deprecated-apis=false`, but I'll make extra sure by testing against the `rustyrussell:guilt/v082-deprecations` branch.

**Comment by shesek** [comment]
I tested, everything seems to work. Cheers!
