### ISSUE TITLE
Fresh Install Stuck on Spinning Wheel

### ISSUE THREAD

**Issue by robbie2121** [shesek/spark-wallet#143]
Hello,

I am running the latest version of windows 10 64-bit and I just downloaded and installed a fresh version of spark on 2 different computers. Both computers have exact same issue:

When I open the wallet for the first time, it just gets stuck on a spinning wheel (seemingly forever?).

Anyone else running into this issue?

**Comment by shesek** [comment]
What installation method did you use? The desktop app or as a web server?

Can you check if any errors show up on the developer console? (you can open it with Ctrl-Shift-I)

**Comment by robbie2121** [comment]
Hi!

I installed the desktop app:
![image](https://user-images.githubusercontent.com/47472623/79899768-148e8500-83c2-11ea-8cee-925041bf853d.png)


Here is the developer console:
![image](https://user-images.githubusercontent.com/47472623/79899745-0e000d80-83c2-11ea-946e-5726f880c73b.png)

Thanks

**Comment by shesek** [comment]
Looks like this got broken in one of the recent releases due to changes in electron (used to package the spark desktop apps). I released [v0.2.14](https://github.com/shesek/spark-wallet/releases/tag/v0.2.14) with a fix, can you try and see if that works?

Thanks for reporting this!

**Comment by robbie2121** [comment]
> Looks like this got broken in one of the recent releases due to changes in electron (used to package the spark desktop apps). I released [v0.2.14](https://github.com/shesek/spark-wallet/releases/tag/v0.2.14) with a fix, can you try and see if that works?
> 
> Thanks for reporting this!

it's working now! Thanks!!
