### ISSUE TITLE
Amount KeySend received correct, amount KeySend sent isn't

### ISSUE THREAD

**Issue by sumBTC** [shesek/spark-wallet#146]
**EDIT**: it's equally true for the `pay` command (for c-lightning v0.9.0rc3). Receiving amount is displayed correctly, sent amount isn't.

I just sent 10 satoshi from my test lightning node to my main lightning node (both running c-lightning v0.9.0rc3) and Spark Wallet correctly displayed (for my main node) the received amount. The description was also correct "Spontaneous incoming payment through keysend"

I then sent 10 satoshi from my main lightning node to my test node and the sent amount was not correctly displayed, only "- sat" is visible. The description for the destination is empty. 

The total balance is correctly updated.

**Comment by cdecker** [comment]
This is an issue on the c-lightning side, where we inadvertently changed the interface for `listsendpays`. See https://github.com/ElementsProject/lightning/pull/3881 for the fix of this issue. I tested it against my Spark node and it works like a charm.

Sorry for breaking this, mea culpa :-)

**Comment by sumBTC** [comment]
Haha well, glad it gets fixed so fast. I'll close the issue when the fix gets merged and I've tested it as well. After having used `sendinvoiceless` for some time now, it's great to see an official and integrated implementation like `KeySend`.

**Comment by sumBTC** [comment]
> it works like a charm

Can confirm!

**Comment by cdecker** [comment]
Thanks for confirming :+1:
