### ISSUE TITLE
Use `listpays` instead of `listsendpays` for the list of outgoing payments

### ISSUE THREAD

**Issue by cdecker** [shesek/spark-wallet#147]
Since c-lightning will start supporting sending of multi-part payments there is no longer a direct relationship between a `sendpay` call (or `sendonion` call which also generates `listsendpays` entries) and the overall payment.

Instead of `listsendpays` spark should use `listpays` which aggregates over all sub-payments and reports the correct amounts and the correct status.

**Comment by cdecker** [comment]
The structure of both results is rather similar btw so it shouldn't be a huge change.

**Comment by shesek** [comment]
Thanks for the heads up! Implemented in https://github.com/shesek/spark-wallet/commit/ee7b46769897d6413261840f97722d6e6ab37cc4.
