### ISSUE TITLE
Android 2.5 debug apk not working

### ISSUE THREAD

**Issue by leblitzdick** [shesek/spark-wallet#149]
Hi,
version 2.4 works but 2.5 fails when connecting.  No error message, just rotating circles ;-)

My server version is up to date 2.5

**Comment by shesek** [comment]
Thanks for the bug report, I'm looking into this.

**Comment by shesek** [comment]
I released v0.2.16, can you check if that fixes your issue?

**Comment by leblitzdick** [comment]
problem solved, thanx!
