### ISSUE TITLE
"This node does not accept incoming connections" ... solution?

### ISSUE THREAD

**Issue by drschwabe** [shesek/spark-wallet#159]
On my node's summary page it says "This node does not accept incoming connections."
i have another node on the same machine (using the same bitcoind instance) that I have also spawned spark-wallet on (using the -l option to specify the node's different dir) and that particular node does not show the same message. 

both are connected to a channel from another node.   the only difference is one has slightly more satoshis in its channel and on-chain balance (the err occurs on the node with slightly less) 

So is this just a liquidity issue; or what specifically causes this message ?    I searched/found https://github.com/shesek/spark-wallet/blob/970fd5ab585f009c26fc433d0aa9c91ec5ca2bd2/client/src/views/node.js#L21 but there are no comments or context other than not having an 'address' ? 

thx for your help; just experimenting and appreciate any tips

**Comment by shesek** [comment]
This isn't related to channels and/or liquidity, it just means that your c-lightning node was not configured to accept incoming connections. You might want to check your `autolisten`, `addr` and `{bind,announce}-addr` config options, which are [documented here](https://github.com/ElementsProject/lightning/blob/master/doc/lightningd-config.5.md#networking-options). I would start by looking for options that are set differently between your two nodes.

**Comment by shesek** [comment]
Oh, and also, did you set a different port for one of your nodes? You should change one to use something different than the default 9735, with i.e. `--addr 0.0.0.0:9739`.

**Comment by drschwabe** [comment]
Thank-you!  After taking your advice and poking around by adding a `~/.lightning/config` file with simply a single line with: `announce-addr=127.0.0.1:9737` (any port) that spark wallet now clears the aforementioned message.
