### ISSUE TITLE
Docker lightning LN_ALIAS and LN_RGB parameters

### ISSUE THREAD

**Issue by CooleRnax** [shesek/spark-wallet#16]
I would great if we were able use docker env variables to change these parameters easily instead of editing config file.

**Comment by CooleRnax** [comment]
This is right implementation?
`LN_ALIAS='my_alias'
LIGHTNINGD_OPT='--rgb my_rgb'`

**Comment by shesek** [comment]
```bash
$ docker run -e LN_ALIAS='my_alias' -e LIGHTNINGD_OPT='--rgb my_rgb' [...] shesek/spark-wallet
```
