### ISSUE TITLE
spark wallet desktop app doesn't match c-lightning values in channel liquidity

### ISSUE THREAD

**Issue by PsySc0rpi0n** [shesek/spark-wallet#168]
OS version: Debian Burst 64bit
Dektop app version: 0.2.17
c-lightning version: v0.9.2-67-gff88308

DESCRIPTION
When I run in terminal, the command _**lightning-cli listpeers**_ I get all the info about open channels, including:
"spendable_msat": "614003000msat",
"receivable_msat": "58896000msat"

but Spark-Wallet shows different values for these fields:
https://i.ibb.co/nLp35jV/image.png

**Comment by shesek** [comment]
What do you see if you enable developer mode (by clicking the version number in the bottom left) and toggle the channel's details?

**Comment by PsySc0rpi0n** [comment]
> What do you see if you enable developer mode (by clicking the version number in the bottom left) and toggle the channel's details?

Check this screenshot I just took
https://i.ibb.co/kcCRTsT/image.png

**Comment by PsySc0rpi0n** [comment]
@shesek any update to this?

**Comment by PsySc0rpi0n** [comment]
25 days and not a single reply after [this](https://github.com/shesek/spark-wallet/issues/168#issuecomment-761799812).

And @shesek you already replied to later issues, but can't reply here anymore?

**Comment by shesek** [comment]
Sorry for the slow reply. Not sure what could be causing this honestly. Are you still experiencing it?

**Comment by PsySc0rpi0n** [comment]
> Sorry for the slow reply. Not sure what could be causing this. Are you still experiencing it?

I think it's all related to the way each software calculates the values they show to the user. Some include the reserve channel values, some don't. Some present the raw values, all separated, some do some obscure math under the hood, so probably, the values presented by Spark Wallet are correct in your own way. But they do not match exactly the same as raw values that c.lightning output in the command line. Anyway, I'm sorry but I'm not using Spark Wallet anymore.

Thanks
