### ISSUE TITLE
How to backup full node?

### ISSUE THREAD

**Issue by CooleRnax** [shesek/spark-wallet#17]
Is there any way?

**Comment by shesek** [comment]
Its basically a directory that you need to backup. With the docker command in the docs, this directory will be at `~/.spark-docker/lightning`. How to back this up exactly is outside the scope of Spark, you should look for advice backing up c-lightning nodes and apply it to that directory (there are some complexities other than just copying the folder).

**Comment by shesek** [comment]
Oh, wait, did you mean the bitcoind or c-lightning node?

If you meant bitcoin, the answer is basically the same (look for backup instructions for bitcoind), only that the files would be at `~/.spark-docker/bitcoin`.

**Comment by CooleRnax** [comment]
Node as I understand consists from bitcoin, lightning and spark, so I need to backup all.

**Comment by shesek** [comment]
So grab the entire `~/.spark-docker` directory and back it up (or whichever directory you mounted in to the container's `/data`).

**Comment by CooleRnax** [comment]
As I understood main files are wallets.dat and hsm_secret

**Comment by shesek** [comment]
You also want the `lightningd.sqlite3` file in the lightning data directory.

**Comment by CooleRnax** [comment]
restoring `lightningd.sqlite3` file will burn you node.
lightningd node currenly can't be fully backed up, only funds can be backed up

**Comment by shesek** [comment]
In any case, I think you should have a backup for the `lightningd.sqlite3` database file. You can figure out later if you can use it or not, but keep it so that you'll have more options. just my 2 sats :)

**Comment by CooleRnax** [comment]
Yep I decided to keep everything exept blockchain data.
