### ISSUE TITLE
BITCOIND_OPT variable not working

### ISSUE THREAD

**Issue by CooleRnax** [shesek/spark-wallet#18]
I have created variable `BITCOIND_OPT='-proxy=xxx:xxx'` in docker
I see bitcoind process, and it doesn't have my custom params.

**Comment by CooleRnax** [comment]
that's because you have `BITCOIND_OPTS` in code

**Comment by shesek** [comment]
It should be `BITCOIND_OPT`, I'll rename it soon. In the meanwhile you should be able to use `BITCOIND_OPTS`.

**Comment by shesek** [comment]
Renamed in 4a66cb0b6c24ac7d08c866348c277a73a3dc5acf, will be part of the v0.1.2 release.
