### ISSUE TITLE
Cannot connect using web browser

### ISSUE THREAD

**Issue by BlockchainBilly** [shesek/spark-wallet#19]
I'm having trouble accessing it through the Web. I ran `spark-wallet -l /path/to/lightning` and got the message with the login details and `HTTP server running on http://localhost:9737`. But when I go to `http://ip_address:9737` or `http://localhost:9737` I get errors., including ERR_CONNECTION_REFUSED and ERR_CONNECTION_TIMED_OUT. I am forwarding port 9737 to the computer running Spark. Any advice?

**Comment by shesek** [comment]
Have you read the [connecting remotely](https://github.com/shesek/spark-wallet#connecting-remotely) section? `http://localhost/` will only work from the same device running Spark. If you're connecting from a different device, you'll need to set `--host` and connect using the IP address.

**Comment by BlockchainBilly** [comment]
Oops, I mistakenly thought I could use another computer on my LAN and access through localhost (rookie mistake).

I was using the article by grubles and it didn't mention --host other than when using LetsEncrypt, so I didn't think to. Thanks for pointing that out. So just to be certain, I use `--host server_external_ip_address` and then connect from a separate computer using `http://server_external_ip_address:9737` ?

**Comment by BlockchainBilly** [comment]
Also sorry for not reading the README in detail, was trying to throw it together quickly before leaving for work!

**Comment by shesek** [comment]
> So just to be certain, I use `--host server_external_ip_address` and then connect from a separate computer using `http://server_external_ip_address:9737`?

Yes. You might also need to setup port forwarding on your router and relax your firewall.

Another option is to use [`--onion`](https://github.com/shesek/spark-wallet/blob/master/doc/onion.md), which will setup a tor hidden service. You don't need to setup port forwarding that way, but you'll need tor on the client side.

**Comment by BlockchainBilly** [comment]
I tried running with `--host` and it said `Loaded TLS certificate with fingerprint ...` follow by this error:
```
uncaughtException, stopping process
Error: listen EADDRNOTAVAIL <MY_IP_ADDRESS>:9737
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1288:19)
    at listenInCluster (net.js:1353:12)
    at doListen (net.js:1479:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by shesek** [comment]
It looks like something else is binding on port 9737. Do you have a previous spark server running? You can try stopping them with `killall spark-wallet`. Or you can start the server on a different port, with `--port <port>`.

**Comment by BlockchainBilly** [comment]
`killall spark-wallet` returns `spark-wallet: no process found`. Starting on different port gives same error. I also did a check to see what is listening on 9737 and nothing was found.

**Comment by BlockchainBilly** [comment]
The user doesn't have sudo privilege and is using testnet3 if that matters. I made the user and all I did was install Core and C-Lightning then Spark

**Comment by BlockchainBilly** [comment]
Not sure if it matters but I installed it globally using my main user to ~/.npm-global and then tried starting it from my btctestnet user using the full path to spark-wallet that I got from `which spark-wallet` on the main user

**Comment by shesek** [comment]
Oh, sorry, that `EADDRNOTAVAIL` error means that the IP address you specified is unavailable, not the port number. Are you sure you're setting the correct IP?

> Not sure if it matters but I installed it globally using my main user to ~/.npm-global and then tried starting it from my btctestnet

This could potentially cause issues, I would suggest you to `npm install` it from the `btctestnet` user. But I don't think its causing that `EADDRNOTAVAIL` error.

**Comment by BlockchainBilly** [comment]
It is the ipaddress I get from www.whatismyip.com and through using `dig` through command line. It seems to be the right address.

I tried running it on mainnet on my main user account and got the same error `Error: listen EADDRNOTAVAIL <MY_IP_ADDRESS>:9737`

**Comment by BlockchainBilly** [comment]
I have had another Node.js server running on this machine, could this be interfering? (Different port). I did try stopping that server and running spark-wallet, which still didn't work. I also forgot to mention that http://localhost:9737 is working fine from the machine running spark-wallet.

**Comment by BlockchainBilly** [comment]
Okay I'm home now so able to test the Google results. `--host 0.0.0.0` made it work, which is apparently "all IPs on this machine." Then I reran using `--host server_internal_ip_address` (instead of external address), which works! Thanks for all of your help with this, now to open up some channels and try the wallet out :)
