### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by sumBTC** [shesek/spark-wallet#20]
I've noticed that the spark wallet uses quite a lot of cpu, while I thought it would be negligible. One reason could be that c-lightning currently has 10 pending payments, which is quite high, and Spark is actively monitoring that. On Ubuntu:

    top -d 60 

tells me that the spark-wallet uses 7% of my cpu. Is this what should be expected and,. if so, what's the reason for this high number?

**EDIT:** all pending transaction are now labeled as failed and the spark-wallet still uses 7% of my cpu (all the time).

**Comment by shesek** [comment]
Note that you can also run the distribution build from the git repo if you run `npm run dist:npm`, then start the server with `./dist/cli.js [args]`.

**Comment by sumBTC** [comment]
I don't use TLS (I think) as I get a warning if I open the spark wallet via my browser on my smart phone.

Downloaded like this:
    git pull https://github.com/shesek/spark-wallet.git

Installed like this:
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

    sudo apt-get install -y nodejs

    git clone https://github.com/shesek/spark-wallet && cd spark-wallet

    npm install

and run like this:
    npm start -- --host 192.168.178.20 --login user:131131111 >& out.txt &

**Comment by shesek** [comment]
Can you try running from the distribution build (https://github.com/shesek/spark-wallet/issues/20#issuecomment-420094482) and see if that changes anything?

**Comment by sumBTC** [comment]
Yes, that completely solved it! The command "top -d 60" now only shows 0.2% cpu, which is what one would expect. For others, I now had to start Spark like this (without the --):

    ./dist/cli.js --host 192.168.178.20 --login username:password >& out.txt &

Thanks a lot and a really great wallet that looks beautiful. You can decide if this is good enough to close the issue.

**Comment by shesek** [comment]
I think it is, `npm start` is meant to start a development environment (with live babel/browserify/stylus/pug transpilation) and is expected to be more resource hungry compared to the distribution build. Thanks for the kind words!

**Comment by shesek** [comment]
> I now had to start Spark like this (without the --):

Yes, the `--` is an npm thing, which is required for passing the arguments to the underlying script. It's not needed if you're invoking the `.js` file directly, or using the `spark-wallet` executable (which you would get by installing with `npm install -g spark-wallet`).
