### ISSUE TITLE
android app does not open

### ISSUE THREAD

**Issue by ManuAgora** [shesek/spark-wallet#203]
I downloaded the app off Aurora Store and when I open I get "error getting referral code" and the so doesn't do anything. I've tried with and without orbot turned on.
![Screenshot_20220618-134808](https://user-images.githubusercontent.com/86299874/174436186-f1c79e5f-360f-46aa-a431-0198f205dbb3.png)

**Comment by ManuAgora** [comment]
I'm an idiot, this is the wrong app

**Comment by ghost** [comment]
@ManuAgora Then close this issue maybe?
