### ISSUE TITLE
Cannot get remote access going

### ISSUE THREAD

**Issue by d4amenace** [shesek/spark-wallet#24]
I installed spark and use this startup command:

npx spark-wallet --login user:pass --host ddns.noip.com –onion true -Q

The first time I did this I saw a QR code and the tls and tor folders where created.  That's when I found out I needed to get a different modem so I could get a ddns from noip.com and use my local pc as a server.  Unfortunately the first time I ran spark it was on the old modem and still had it's old tls keys and tor keys.  Now with the new modem (and ip) spark will not create a new tls or tor folder even when commanded...

When I start spark this is all I see....

![7 1](https://user-images.githubusercontent.com/29969146/45593512-f216c900-b94d-11e8-9d93-5a6afb2d0272.png)

My spark wallet conf file:

login=user:pass
port=9738
host=ddns.noip.com
onion=true
pairing-qr=true
no-tls=true

What am I missing?  I have opened port 9738 (spark) and 9737 (lightning).......  set up ddns on router ....did not setup dhcp as it was not optional on TP-Link TC-W7960.

**Comment by shesek** [comment]
@d4amenace I'm closing this, please report back if you're still having issues.

**Comment by d4amenace** [comment]
Thx...this did it.
