### ISSUE TITLE
Spark-wallet displays total balance independent of connection status

### ISSUE THREAD

**Issue by sumBTC** [shesek/spark-wallet#26]
I had a few nodes that were disconnected as indicated by c-lightning:
   "connected": false. 

I noticed that the total balance was the same as when they were connected.
This may be a design choice but I think it's much more logical to show the "spendable" balance.

**Comment by shesek** [comment]
Implemented in 8bda5984131fe6a066eeb6908641d8dc89349656, thanks for suggestion @sumBTC!
