### ISSUE TITLE
Docker image upgrade issue

### ISSUE THREAD

**Issue by CooleRnax** [shesek/spark-wallet#29]
I have upgraded the image but wallet and bitcoind didn't upgraded.

**Comment by shesek** [comment]
How did you determine they were not updated? Can you open a bash session inside the container and check `bitcoind -version` and `lightningd --version`?

**Comment by CooleRnax** [comment]
**spark 0.1.1 (from wallet interface)**
bitcoind 0.16.3
lightningd 0.6

**Comment by shesek** [comment]
Note that the most recent Spark release is v0.1.2 (available on [docker hub](https://hub.docker.com/r/shesek/spark-wallet/tags/)).

What wasn't upgraded properly exactly? I'm still not sure I understand the reported issue.

**Comment by CooleRnax** [comment]
Actually spark didn't upgraded, or it reports wrong version over the web.
I thought that bitcoind didn't upgraded too, but it actually did.

**Comment by shesek** [comment]
Have you restarted Spark after pulling the new image?

**Comment by CooleRnax** [comment]
ofc

**Comment by shesek** [comment]
Are you still experiencing this? Please re-open the issue if so.
