### ISSUE TITLE
Install multiple spark wallets on same machine running all at startup

### ISSUE THREAD

**Issue by d4amenace** [shesek/spark-wallet#34]
I was wondering if it is possible to run multiple instances of spark on the same machine? 

1:  How do I install to multiple folders?

npm install -g spark-wallet 2
npm install -g spark-wallet 3
??  etc.......

2: What needs to be different in config?

spark port
lightning directory for each spark
Anything else?

3. How do I make all installs initiate at start up?  When I run them will the execution commands follow the folder names ( $ spark-wallet_2  <arg>)?

**Comment by d4amenace** [comment]
Followed your steps:  My config.....

host=localhost

port=8902

onion=true

login=user:xxxx

print-key=true

pairing-qr=true

onion-path=/home/primary/.spark-wallet/2/tor/

tls-path=/home/primary/.spark-wallet/2/tls/

ln-path=/home/primary/.lightning2/


Execute startup of 2nd C-lightning with this:

spark-wallet --config=/home/primary/.spark-wallet/2/config

Output in terminal:


primary@TestNode:~$ spark-wallet --config=/home/primary/.spark-wallet/2/config
Connected to c-lightning v0.6.1-225-g7eec225 with id 03be0c4bef8de4883a98e8a46b14a64627f2f691b4c76af9ab453084a629a752f1 on network bitcoin at /home/primary/.lightning2/lightning-rpc
Loaded TLS certificate with fingerprint 35:e3:07:b3:d9:71:2f:10:0a:09:12:6a:81:d9:44:54:67:a7:42:8a from /home/primary/.spark-wallet/2/tls/
Access key for remote API access: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

HTTPS server running on https://localhost:8902

Tor Onion Hidden Service v3 running on http://2oks2nxaw6xp7dx437u5eerciaapk3nueepffxa4vqd67b6uzhhpinad.onion

When I go to the local host it does not connect.  Also, there is nothing "posting" like a working spark server on terminal.

The access key is also unchanged from the first Spark server.  Can I change this?  What am I missing to get the 2nd working......

**Comment by shesek** [comment]
> When I go to the local host it does not connect (It hangs on "performing tls handshake" and then times out). 

If you're connecting over `localhost`, you don't really need TLS. Can you try turning TLS off (remove `tls-path` from your config) and see what happens then?

> The access key is also unchanged from the first Spark server. Can I change this?

The access key is derived from the username:password combo defined in `login`. Changing the `login` would give you a different access key.

**Comment by d4amenace** [comment]
I have tried removing TLS and I can indeed connect to spark wallets but I have no SSL security.

**Comment by shesek** [comment]
Are you seeing any errors from the server on the console when trying to access Spark over TLS?

**Comment by shesek** [comment]
Closing this for now, please report back if you need more assistance.
