### ISSUE TITLE
Two payment bugs

### ISSUE THREAD

**Issue by rustyrussell** [shesek/spark-wallet#35]
1. Blockstream store uses LIGHTNING: prefix on payment request, which needs to be stripped before handing to c-lightning.
2. 0.6.2 gets upset with upper case (that's a bug, will fix!).  Maybe lower-case the invoice in the mean time?

**Comment by shesek** [comment]
1. The `lightning:` prefix should already be stripped, regardless of its casing. I just tried scanning a QR with an all-uppercase `LIGHTNING:` prefix, and it was stripped.

2. Implemented in 0d1a58f46a1c2da9a16fce04da1a6d424402618a

**Comment by shesek** [comment]
Should be fixed, please report back if you're still experiencing this.
