### ISSUE TITLE
Spark-wallet Docker Diployment : lightningd: Wallet network check failed.

### ISSUE THREAD

**Issue by emonazad** [shesek/spark-wallet#37]
Greetings, i have installed spark-wallet with docker deployment .

I already have a bitcoind and lightning node running at docker. both are working fine.
Container name : lightning1.
host/volume:path in container = /home/123/lighting1:/root/.lightning

i used this command to install spark-wallet

docker run --name spark1 -v /home/123/lightning1/:/root/.lightning/ -p 4737:4737 shesek/spark-wallet -login test:pass

i also tried

docker run --name spark1 -v /home/main/lightning1/:/root/.lightning/ network container:bitcoind -v /123/main/bitcoin/:/root/.bitcoin/ -p 4737:4737 shesek/spark-wallet 

but it seems to giving me a error 

Starting bitcoind... waiting for cookie... waiting for RPC... ready.
Starting lightningd... waiting for RPC unix socket... lightningd: Wallet network check failed.

whats the issue ? Thanks in Advance .

**Comment by shesek** [comment]
You need to mount the lightning data directory to `/etc/lightning`. So `-v /home/123/lightning1/:/etc/lightning`. See the [docker docs](https://github.com/shesek/spark-wallet/blob/master/doc/docker.md) for more details.
