### ISSUE TITLE
Price not updating on idle node

### ISSUE THREAD

**Issue by d4amenace** [shesek/spark-wallet#38]
Hello,

I have noticed peculiar behavior from Spark server.  I have noticed that the USD price has halted updating and has retained a price from days ago!  I thing it may be my server needs restarting....I am not sure.

Here is a pictured of the price displayed on the app and the terminal curl output.....
I haven't used the wallet for days.....perhaps it is only updating when used???
![screenshot_20181110-112748_spark](https://user-images.githubusercontent.com/29969146/48304420-f4754980-e4de-11e8-8eec-b280ed7f38ff.jpg)
![img_20181110_233212](https://user-images.githubusercontent.com/29969146/48304422-f939fd80-e4de-11e8-84d2-c8d82d4d4d95.jpg)

**Comment by d4amenace** [comment]
I believe I know the source of this issue.....the script to make price updates go idle is set to 10000 as a wait period before price updates.....which is close to 3 hours!  This could be dangerous for a consumer who opens up their app after a few days to make a purchase!

**Comment by shesek** [comment]
Closing, please report back if you're still experiencing this issue.
