### ISSUE TITLE
npm install -g spark-wallet does not work

### ISSUE THREAD

**Issue by renepickhardt** [shesek/spark-wallet#4]
I followed what you are describing in https://medium.com/@notgrubles/spark-a-new-gui-for-c-lightning-2cf2f024500c but `$ npm install -g spark-wallet` I guess I have to run as sudo or omit the `-g` flag? 

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rpickhardt/npm-debug.log

**Comment by shesek** [comment]
Awesome. :)

Another alternative is to use `npx` (requires npm v5.2 or newer), which will install the package locally and start it in one go, no `sudo` necessary: `$ npx spark-wallet -l /path/to/lightning ...`

This will, however, have to setup the package again every time its called, so its really more for quick experimentation. You should still `npm install` for repeat use.
