### ISSUE TITLE
Balance mismatch

### ISSUE THREAD

**Issue by NicolasDorier** [shesek/spark-wallet#52]
Why my balance is below the sum of my two last payments?

![image](https://user-images.githubusercontent.com/3020646/50818388-26355000-136a-11e9-8567-6c8cbd5d3110.png)

**Comment by NicolasDorier** [comment]
Closing this, I found out that my channel has been closed and it is in my onchain funds.

It would be great if spark give this information.

**Comment by shesek** [comment]
I wasn't sure how to go about this. Do you think the top-right balance should include onchain funds? Seems kinda confusing, given that the "Pay" functionality wouldn't actually be able to use these funds...

**Comment by NicolasDorier** [comment]
I think you can just show both and maybe play with the font size to distinguish both. "Off Chain X BTC" and 
 below "On Chain X BTC" where On Chain has smaller font size.
