### ISSUE TITLE
UI does not load on ubports phone

### ISSUE THREAD

**Issue by ulrichard** [shesek/spark-wallet#54]
When I try to visit the website of my spark wallet from my phone, the UI doesn't load. Just the three parts of the circles turn around and around.

I think the browser in ubports is the following:
https://github.com/ubports/morph-browser

**Comment by JavierRSobrino** [comment]
![imagen](https://user-images.githubusercontent.com/6039997/51003636-e9b74f00-1537-11e9-8cee-8b46a5763656.png)
Same issue, after a second this msg appears. I have checked that the key is the same. The wallet works in the desktop browser only.

**Comment by hillelt** [comment]
I think TLS mode is not working (see #55). Try starting spark with `--no-tls` and you might be able to connect (albeit security will be an issue).

**Comment by shesek** [comment]
I haven't tested with ubports or morph browser and don't have an easy way to test on them. Does it have some sort of an error console you could look for clues?

@JavierRSobrino Were you able to access it remotely using a desktop browser, or was it from same machine over `localhost`?

**Comment by ulrichard** [comment]
After the last upborts update, it works much better, as long as I am in the local network. This is with TLS enabled. 
The rest is probably for another issue.

**Comment by JavierRSobrino** [comment]
> @JavierRSobrino Is this with the android app or with the android web browser? If it was with the android app, can you check to see if that works with the browser?

It worked with Chrome for Android, but not in the wallet app.
I ended up creating a reverse proxy for it and now it works with the app too, but this is a personal solution, the problem remains I think.

**Comment by shesek** [comment]
> It worked with Chrome for Android, but not in the wallet app.

This might be related to the self-signed TLS certificate. Android won't let apps communicate with servers that has untrusted TLS certificates, and there's no prompt allowing you to make a security exception like you get with the browser. There are two ways to make the certificate trusted:

1. If you can point a domain or subdomain at your IP, you can use the [LetsEncrypt integration](https://github.com/shesek/spark-wallet/blob/master/doc/tls.md#letsencrypt-integration) to get a CA-signed certificate that works smoothly everywhere.

2. You can [manually add the certificate to the Android keyring](https://github.com/shesek/spark-wallet/blob/master/doc/tls.md#add-as-trusted-certificate-to-android) on your device, which would allow Spark to communicate with the existing self-signed certificate.

Another alternative is [setting up the connection over a tor hidden service](https://github.com/shesek/spark-wallet/blob/master/doc/onion.md), which other than the security benefits, also makes it much easier to accept remote connections (without setting up port forwarding etc). The downside is that you'll to setup [Orbot](https://play.google.com/store/apps/details?id=org.torproject.android) on your Android and run it alongside the Spark app.

**Comment by JavierRSobrino** [comment]
@shesek for some reason, adding the certificate to the android keyring didn't worked out. I didn't investigated further because I just used a reverse proxy with letsencrypt in docker, and everything worked like a miracle.
