### ISSUE TITLE
Can't connect via TLS

### ISSUE THREAD

**Issue by hillelt** [shesek/spark-wallet#55]
I installed spark from npm (v0.2.2) and I can connect locally. However, when starting the server with `spark-wallet -i 0.0.0.0` and browsing to `https://<internal_ip>:9737` my web browser times out trying to establish connection. The client machine is a different box on my home network and I tried connecting with Firefox, Chrome and Brave, all timing out in the same fashion.

Note that I can telnet to the internal ip and the server machine is responsive. It seems like something in the TLS handshake might be broken.

On the server:
```
>> spark-wallet -i 0.0.0.0
...
HTTPS server running on https://0.0.0.0:9737
```

On the client (browsers timing out, telnet is working):
```
>> telnet <internal_ip> 9737
Trying x.x.x.x...
Connected to ubuntu-server.
Escape character is '^]'.
```

**Comment by hillelt** [comment]
Also, if I start spark with `spark-wallet -i 0.0.0.0 --no-tls` then I can connect from remote machines -- the problem is definitely with TLS.

**Comment by shesek** [comment]
Can you try making a request from a remote machine using `curl --verbose https://<internal_ip>:9737` and report the output here?

**Comment by hillelt** [comment]
Yes. When I run it it gets stuck for a couple of minutes in the following state:
```
>> curl --verbose https://<internal_ip>:9737
* Rebuilt URL to: https://<internal_ip>:9737/
*   Trying <internal_ip>...
* TCP_NODELAY set
* Connected to <internal_ip> (internal_ip) port 9737 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /home/<my_user>/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
```
and then prints the error below and exits:
```
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to <private_ip>:9737 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to <private_ip>:9737
```

**Comment by shesek** [comment]
Are you able to access it from the same host running the server using `curl -v https://localhost/`?

**Comment by hillelt** [comment]
No, I can't. It fails with essentially the same error (changing the issue title to reflect).

**Comment by sumBTC** [comment]
I have the same problem and can't use Spark wallet anymore (except with --no-tls).

**Comment by shesek** [comment]
@hillelt @sumBTC  which OS and nodejs version are you using?

Btw, another alternative that you could consider is using [`--onion`](https://github.com/shesek/spark-wallet/blob/master/doc/onion.md). This will start a hidden service that you could connect to from everywhere, without worrying about NATs and router configuration. You also get strong encryption with a key that is pinned to the `.onion` hostname (so you don't need CAs). This doesn't require pre-installing Tor on your system, should (hopefully) Just Work ™. :)

**Comment by astupidmoose** [comment]
Can confirm, also cannot open without the --no-tls flag. Simply goes to connection refused

**Comment by k3tan25** [comment]
can also confirm, cannot open without the --no-tls flag.

**Comment by hillelt** [comment]
By the way, I just found out that my router (Bezeq Be) comes with a "secure surfing" protection that randomly blocks me from establishing secure connections with certain web-sites (e.g. Tor). Not sure yet but I have a feeling the problems might be related.

**Comment by pseudozach** [comment]
Having the same issue on debian. port allowed on firewall but https fails. --no-tls works.
no luck with my certificates or lets-encrypt either.

**Comment by scottshapiro** [comment]
Same issue on Ubuntu 16. Can't access remotely.

**Comment by hillelt** [comment]
@shesek  see also https://github.com/mimblewimble/grin/issues/2523 (maybe an opportunity for cross pollination: solutions like i2pd might be relevant for spark or maybe some of the work on spark-wallet could be relevant to grin).

**Comment by Alko89** [comment]
I am unable to open even with --no-tls flag. Keeps redirecting to https.

**Comment by pseudozach** [comment]
As a workaround I managed to get https working with [ngrok](https://dashboard.ngrok.com/get-started)
Run spark regularly on localhost and start ngrok to tunnel the port to remote https domain. 
Tested and works with both spark and [KwH](https://addons.mozilla.org/en-US/firefox/addon/kwh).

**Comment by sumBTC** [comment]
@shesek After trying to tweak tls/ssl for Ubuntu for days and not being able to connect via `openssl s_client -connect IP:9737 (local or external IP)`, I decided to look at `tls.js`. I managed to get spark-wallet working over tls (so without --no-tls) in a browser. The App still can't connect but maybe my solution gives you enough information to get the App working as well. 

In tls.js I had to change `socket.resume();` into `process.nextTick(() => socket.resume());` and that make spark-wallet finally work in a browser without --no-tls.

See the comment (As of NodeJS 10.x ...) in your own [hint](https://stackoverflow.com/a/42019773/865693). I don't understand why the App still refuses to connect.

**Comment by shesek** [comment]
@sumBTC Thank you! I was finally able to reproduce the issue by upgrading to nodejs 10 and was able to resolve it by resuming the socket asynchronously as you suggested. I implemented this in https://github.com/shesek/spark-wallet/commit/3fc7e1a7d5a271869a1823cbbd5882151954f8f6.

> I don't understand why the App still refuses to connect. I have added the TLS certificate (cert.pem) as a user trusted certificate.

I'm not entirely sure, but I think that some Android versions/configurations may not respect user-trusted certificates for connections made by apps (and block the requests). It worked for me when I tried it awhile back (I normally use onion), but I've heard of others having issues.

>  the QR-code isn't read

Which browser and version are you using?

I'm wondering if this is also somehow related to the user-trusted self-signed tls certificate. Websites without tls or with invalid certs are not allowed to access the camera, perhaps this restriction is still in place for websites with user-trusted certs?

I'll try to look a bit more into how user-trusted certs affect these two issues. Would it be possible for you to point some (sub)domain at your IP address and try the letsencrypt integration, to help pinpoint if the self-signed cert is the cause?

**Comment by sumBTC** [comment]
> I was finally able to reproduce the issue

Glad to hear that because if you can't reproduce an issue it's kind of impossible to solve it.

> Websites without tls or with invalid certs are not allowed to access the camera

But I am allowed to access the camera when tls is working.

> Which browser and version are you using?

I tried it with  Google Chrome (79.0.3967.93) and Firefox (6.8.30) (on my android (9) phone). Both give me permission to use the camera and start scanning the QR code for Pay but are never able to read it and report back what's in the QR-code while other scanners report back immediately (including the spark-wallet App)

Am I right that Pay will not except any QR-code but only specific QR-codes that are valid invoices? If so, I think the problem lies there. The QR-code is not seen as valid for some reason.

**Comment by shesek** [comment]
Alright, seems like the original issue here was (finally!) resolved. I created #134 and #135 to keep track of the other two issues raised by @sumBTC.
