### ISSUE TITLE
Can't update UI in chromium

### ISSUE THREAD

**Issue by kallerosenbaum** [shesek/spark-wallet#57]
After updating the spark-wallet server to the latest and greatest version (0.2.2), my android spark app reflects the update by displaying v0.2.2 in the bottom left corner of the screen, but my chromium browser displays v0.2.0.

I've seen the same issue when updating 0.1.2 to 0.1.3 (if I remember correctly) and from 0.1.3 to 0.2.0.

I didn't bother to dig into it until today while the server was still running 0.2.0 and I eventually managed to get the UI in Chromium to update to v0.2.0 by clicking random clear cache buttons and using developer tools, ie Application->Clear storage.

Then I updated from 0.2.0 to 0.2.2, and the same issue happens in chromium. Now I'm stuck with v0.2.0 in chromium.

What's the procedure to get chromium up to date?

**Comment by shesek** [comment]
Yes, the cache is a bit aggressive because its managed by a service worker. Doing a hard-reload with Ctrl-Shift-R should clear everything and get you the new version. If that doesn't work, you can try clearing your browser cache entirely. I'll try looking into ways to make that happen automatically when updating to a new version.

**Comment by shesek** [comment]
I created #59, will keep track of the progress there. I'm closing this issue, but please feel free to write back if you're still having troubles clearing the cache.

**Comment by kallerosenbaum** [comment]
Ctrl-Shift-R does not work for me in chromium. Additional clearing browser cache doesn't help either. What do you mean with clearing browser cache "entirely"?

Sure, closing this and creating a new one that seems OK to me, but short term I'd still like to get my UI updated.

**Comment by shesek** [comment]
Weird, Ctrl-Shift-R does seem to work for me.

Try opening `chrome://settings/clearBrowserData`, go to "Advanced" tab, change "Time Range" to "All time", tick "Cached images and files" and "Hosted app data", untick the others, and click "Clear data".

> my android spark app reflects the update by displaying v0.2.2 in the bottom left corner of the screen, but my chromium browser displays v0.2.0.

Note that the version displayed in the android app is that of the app itself, not of the server. Are you entirely certain the server is upgraded? Can you verify by running `spark-wallet --version`?
