### ISSUE TITLE
Desktop wallet not connecting to remote server

### ISSUE THREAD

**Issue by Razer0123** [shesek/spark-wallet#58]
I've set up a server which is working, because I can connect via browser, but it's impossible for me to connect to it via desktop app, I get "Error: Connection to server lost."

**Comment by shesek** [comment]
Do you have a trusted TLS certificate, or do you have to click-through the TLS warning and add an exception when browsing from the browser?

**Comment by Razer0123** [comment]
I have to click-through the TLS warning

Is the TLS certificate mandatory?

**Comment by shesek** [comment]
I'm afraid so. :( The browser environment inside the Electron desktop app doesn't prompt the user to add an exception, it just blocks communication with the server entirely. The Cordova mobile app behaves the same way as well. Using the standard web browser is the only way to click-through the warning and make it work with an untrusted certificate.

The good news is that [its pretty easy](https://github.com/shesek/spark-wallet/blob/master/doc/tls.md#letsencrypt-integration) to setup a CA-signed certificate using LetsEncrypt, assuming you're able to point a domain or subdomain at your IP address.

**Comment by Razer0123** [comment]
If I understood correctly this means I have to buy a domain, is this correct?

Seems like an overkill just to connect via app :)

**Comment by shesek** [comment]
You could use a free subdomain from a dynamic dns service (like [noip](https://www.noip.com/)), but they sometimes run into rate limits (letsencrypt have a per-domain daily rate limit for registering new certificates). If you could find a less popular free dynamic dns provider (there are quite a few of them) this should work more smoothly.

**Comment by Razer0123** [comment]
Funny you mention that, I already have a DNS hostname on NOIP

I've run this command

`sudo setcap 'cap_net_bind_service=+ep' /opt/Spark/spark-desktop
`
Then

`spark-wallet --host host.com --letsencrypt noipmail
`

Doesn't seem to work

`
You don't have prmission to bind on 0.0.0.0:80.
See https://github.com/shesek/spark-wallet/blob/master/doc/tls.md#letsencrypt-integration for advice.
`

Could this be because of the daily rate limit?

**Comment by shesek** [comment]
> `sudo setcap 'cap_net_bind_service=+ep' /opt/Spark/spark-desktop `

You should do this for the nodejs process, not for spark itself. Like so: `sudo setcap 'cap_net_bind_service=+ep' $(which node)`

Also note that `spark-desktop` and `spark-wallet` are different. `spark-wallet` is the web server you can install from `npm`, while `spark-desktop` is the Electron desktop app.

> Doesn't seem to work
>
> `You don't have prmission to bind on 0.0.0.0:80. See https://github.com/shesek/spark-wallet/blob/master/doc/tls.md#letsencrypt-integration for advice.`
>
> Could this be because of the daily rate limit?

This isn't related to the daily limit, its a permission issue because of the port. Running `setcap` as above should fix this.

**Comment by Razer0123** [comment]
Tried, this is what I got

`Setting up LetsEncrypt CA-signed TLS cert for dnscasa789.mynetgear.com with email alterego.client@icloud.com in /home/alessandro/.spark-wallet/tls
Starting LetsEncrypt verification server
uncaughtException, stopping process
Error: listen EADDRNOTAVAIL 79.12.185.15:9737
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
`

**Comment by Razer0123** [comment]
Nothing is running on 9737

```
alessandro@alessandro-pc:~/lightning$ lsof -i :9737
alessandro@alessandro-pc:~/lightning$ sudo netstat -tulpn | grep :9737
alessandro@alessandro-pc:~/lightning$ 

```

**Comment by shesek** [comment]
Try binding on `0.0.0.0` (all interfaces) and set the certificate hostname via `--tls-name`. For example:

```bash
$ spark-wallet --host 0.0.0.0 --letsencrypt razer012@foo.com --tls-name razer012.noip.com
```

**Comment by Razer0123** [comment]
This seems to have worked!

Unfortunately now I can't connect to the server from another location

```
[acme-v2] handled(?) rejection as errback:
Error: connect ETIMEDOUT IP:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
Error loading/registering certificate for 'dnsname':
{ Error: connect ETIMEDOUT IP:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'IP',
  port: 80 }

```

**Comment by shesek** [comment]
Are you able to otherwise accept connections on port 80? You can check with `netcat` like so:

```bash
$ sudo apt install netcat
$ killall spark-wallet # stop any running spark instances

# listen for connections on port 80
$ nc -v -l 0.0.0.0 80 

# from a different terminal, try connecting using your public IP address:
$ nc -v <public-ip> 80

# you can use this to automatically get your ip:
$ nc -v `curl ifconfig.me` 80
```
