### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by iraamaro** [shesek/spark-wallet#6]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by shesek** [comment]
Hi @hanelore. The first step would be making Spark translatable, by changing all English texts with calls to an i18n library like [polyglot](https://github.com/airbnb/polyglot.js) or [i18next](https://github.com/i18next/i18next) (I don't have experience with either).

I created #9 to keep track of that.
