### ISSUE TITLE
QR code isn't shown if public URL isn't set

### ISSUE THREAD

**Issue by jonasnick** [shesek/spark-wallet#70]
Expected behavior:
Running spark-wallet with `-Q` prints the QR code

Actual behavior:
It just ignores `-Q` if the public URL isn't set (https://github.com/shesek/spark-wallet/blob/e1c7018c3120336be2e1f5d4c0ea94b8c3be2146/src/app.js#L74). Ideally spark-wallet would log a warning to show what the problem is.

**Comment by shesek** [comment]
Thanks for the report! Changed as suggested in 0cee6f2605eb200885bcf4cda6c065e1bd581934. Cheers. :)
