### ISSUE TITLE
Unknown command 'pay'

### ISSUE THREAD

**Issue by Kexkey** [shesek/spark-wallet#75]
Hi, when trying to pay an invoice, I get the error message "Unknown command 'pay'" on a red background.

Spark-wallet 0.2.5
C-lightning 0.7.0

I saw issue #61 that seems to be similar, but I am not sure what the fix is.

Thanks for your support!

**Comment by shesek** [comment]
`pay` became a plugin in v0.7, is there any chance you have it turned off for some reason?

Are you able to call `pay` using `lightning-cli`?

**Comment by Kexkey** [comment]
Hey thanks shesek, you were right!  Tag 0.7.0 of c-lightning dockerfile seems to have that unexpected outcome wrt plugins.  I fixed it in our docker image after seeing the PR's over there.  Thanks!
