### ISSUE TITLE
Allow disabling price lookup

### ISSUE THREAD

**Issue by hkjn** [shesek/spark-wallet#81]
Related to #78.

It would be cool if users could set a flag like `--disable-rates` to tell spark-wallet to not look up fiat exchange rates at all, thus reducing dependencies on third party servers and potentially improving privacy.

**Comment by shesek** [comment]
Implemented in 7512aa98a87364d05bb6455533f939dc0a22dac7, can be set with `--no-rates`.

Spark will currently show USD amounts as "n/a" if you pick USD as your display unit. Ideally, the client-side should be made aware that exchange rates is off and avoid displaying USD as an option altogether. I created a separate ticket to keep track of that at #82.
