### ISSUE TITLE
[Feature request] ARM32 docker image

### ISSUE THREAD

**Issue by NicolasDorier** [shesek/spark-wallet#89]
I plan to work on this, because that's the only reason why BTCPay does not support clightning on raspberry. 

It would greatly simplify the work if I can make it works for STANDALONE only.

Would you accept a PR if I strip non standalone parts for arm32?

**Comment by shesek** [comment]
Yes, I'm fine with the arm32 image being standalone only and not support the bundled bitcoind/lightningd. A PR would be appreciated, thank you!

**Comment by NicolasDorier** [comment]
A new release would be awesome
