### ISSUE TITLE
android app camera

### ISSUE THREAD

**Issue by k3tan172** [shesek/spark-wallet#91]
android app camera not opening when trying to scan a QR code to send funds. could be my phone, but please check?

**Comment by shesek** [comment]
Which android device are you using? I'm unable to reproduce with v0.2.7.

**Comment by k3tan172** [comment]
I'm using a Oneplus One. 
OS is LineageOS 16.
Screenshot attached.
![photo6327794516156852432](https://user-images.githubusercontent.com/44537874/59130765-af9d8c80-89b3-11e9-8510-506ffcc5cbaf.jpg)

**Comment by shesek** [comment]
Did you see the request to get camera permissions?

**Comment by k3tan172** [comment]
I did not see the request. However camera permissions are granted. I upgraded from the playstore if that's worth anything.
![photo6329900372981819462](https://user-images.githubusercontent.com/44537874/59137422-1f6b4180-89cb-11e9-8937-db5a8ee53513.jpg)
.

**Comment by shesek** [comment]
The same issue was also reported by @instagibbs. It appears like it was introduced in v0.2.6 and that downgrading to v0.2.5 fixes it. I'm still unable to reproduce this on my device, will try a few more to try and diagnose this.

**Comment by shesek** [comment]
Found the source of this bug and fixed it in https://github.com/shesek/spark-wallet/commit/377ea398e25d8ec810a171eadefadfa2fdaf28e0. This was only happening with the dark themes, which is why I wasn't able to reproduce... >_<

This should be released soon in v0.2.8.

**Comment by instagibbs** [comment]
Yay
